name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: tshirts fail
      run: |
        g++ -Wall -Wextra -Werror tshirts.c -o tshirts.out

    - name: misaligned fail
      run: |
        g++ -Wall -Wextra -Werror misaligned.c -o misaligned.out

    - name: alerter fail
      run: |
        g++ -Wall -Wextra -Werror alerter.c -o alerter.out
